channels:
- conda-forge
- defaults
dependencies:
  - python >=3.11,<3.12
  # build
  - doit[toml]
  - conda-lock
  - pip 
  # test
  - pytest
  # protyping
  - bqplot
  - traitlets
  - ipython 
  - ipywidgets 
  - jupyterlab >=3.6,<4.0.0a0
  - jupyterlab_widgets 
  # runtime  
  - numpy
  - pydoe2
  - openmdao
